

// Each new term in the Fibonacci sequence is
// generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose
// values do not exceed four million, find the
// sum of the even-valued terms.

pub(crate) fn main() {
    println!("euler2.rs");
    let mut tail = 0;
    let mut head= 1;
    let mut accumulator = 0;
    let four_million = 4000000;
    
    while head <= four_million {
        if head % 2 == 0 {
            accumulator = accumulator + head;
        }
        
        let new_tail= head;
        let new_head = tail + head;
        
        tail = new_tail;
        head = new_head;
    }
    
    println!("euler2 answer: {}", accumulator );
}
